#!/bin/sh
# Xcode Cloud post-clone script — generates Config.xcconfig from secrets, then
# generates the Xcode project from project.yml.
set -e

cd "$CI_PRIMARY_REPOSITORY_PATH/apple/OpenBrain"

# Write Config.xcconfig from Xcode Cloud environment variables.
# Set OPENBRAIN_API_URL as a secret environment variable in App Store Connect
# under your Xcode Cloud workflow → Environment → Environment Variables.
echo "Writing Config.xcconfig..."
cat > Config.xcconfig <<EOF
// Auto-generated by ci_post_clone.sh — do not commit
API_BASE_URL = ${OPENBRAIN_API_URL:?OPENBRAIN_API_URL secret must be set in Xcode Cloud workflow environment variables}
EOF

echo "Installing XcodeGen..."
brew install xcodegen

echo "Generating project..."
xcodegen generate
